[theme]
primaryColor="#00189E"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#768DF3" 
textColor= "#000000"
font="sans serif"

# Para cores, podemos usar os formatos: "green", "#FFDE5A" ou RGB(61,183,228)
# Para fontes estão disponíveis: "sans serif", "serif", "monospace"
# Pode-se usar uma tema base, com base="light", e fazer alterações

# secondaryBackgroundColor é a cor de fundo do sidebar e menu