[connections.mssql+pyodbc]
url = URL.create(
    "mssql+pyodbc",
    username="DESKTOP-62QBI08\james",
    password="47297913",
    host="DESKTOP-62QBI08\WINCCPLUSMIG2014",
    port=51304,
    database="SSMM",
    query={
        "driver": "ODBC Driver 18 for SQL Server",
        "TrustServerCertificate": "yes",
        "authentication": "ActiveDirectoryIntegrated",
    },
)
engine = create_engine(url)

conn = engine.connect()