[connections.mssql+pyodbc]
url = URL.create(
    "mssql+pyodbc",
    username="SALES",
    password="47297913",
    host="DESKTOP-62QBI08\WINCCPLUSMIG2014",
    port=51304,
    database="SMMI",
    query={
        "driver": "ODBC Driver 18 for SQL Server",
        "TrustServerCertificate": "yes",
        "authentication": "ActiveDirectoryIntegrated",
    },
)