[connections.mssql+pyodbc]
url ="mssql+pyodbc://DESKTOP-62QBI08\james:47297913@DESKTOP-62QBI08\WINCCPLUSMIG2014:51304/SMMI?"
    "driver=ODBC+Driver+18+for+SQL+Server&TrustServerCertificate=yes"
    "&authentication=ActiveDirectoryIntegrated"
username="SALES"
password="47297913"
host="DESKTOP-62QBI08\WINCCPLUSMIG2014"
port=51304
database="SMMI"


